### PR TITLE
Migrate Runtime and Custom Events docs

### PR DESCRIPTION
**Pull request by icaraps**
Migrated content: 
* https://developer-stage.adobe.com/app-builder/docs/overview/firefly_and_runtime/
* https://developer-stage.adobe.com/app-builder/docs/overview/community/ (Social media and support from Runtime)
* https://developer-stage.adobe.com/app-builder/docs/overview/faq/ (Runtime questions at the end of the page)
* https://developer-stage.adobe.com/app-builder/docs/guides/runtime/ 
* https://developer-stage.adobe.com/app-builder/docs/guides/events/custom-events/

### CODE REVIEW

**Comment by icaraps** [comment]
Goes together with https://developer-stage.adobe.com/events/docs/ and https://developer-stage.adobe.com/console/docs

**Comment by icaraps** [comment]
ping @sarahxxu

**Comment by rperelma** [comment]
@sarahxxu is out this week. @kgera can you review, please?

**Comment by purplecabbage** [comment]
Can this be merged or closed?

**Comment by purplecabbage** [comment]
Closing due to inactivity

**Pull request closed without merging**
